## static_countries
UPDATE static_countries SET cn_short_hr='Andora' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_hr='Ujedinjeni Arapski Emirati' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_hr='Afganistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_hr='Antigua i Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_hr='Anguila' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_hr='Albanija' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_hr='Armenija' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_hr='Nizozemski Antili' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_hr='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_hr='Antarktika' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_hr='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_hr='Američka Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_hr='Austrija' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_hr='Australija' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_hr='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_hr='Azerbajdžan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_hr='Bosna i Hercegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_hr='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_hr='Bangladeš' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_hr='Belgija' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_hr='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_hr='Bugarska' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_hr='Bahrein' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_hr='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_hr='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_hr='Bermuda' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_hr='Brunej' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_hr='Bolivija' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_hr='Brazil' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_hr='Bahami' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_hr='Butan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_hr='Otok Bouvet' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_hr='Bocvana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_hr='Bjelorusija' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_hr='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_hr='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_hr='Kokosovi Otoci' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_hr='DR Kongo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_hr='Centralnoafrička republika' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_hr='Kongo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_hr='Švicarska' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_hr='Obala Bjelokosti' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_hr='Kukovi Otoci' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_hr='Čile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_hr='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_hr='Kina' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_hr='Kolumbija' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_hr='Kostarika' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_hr='Kuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_hr='Zelenortska republika' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_hr='Božićni Otoci' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_hr='Cipar' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_hr='Češka' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_hr='Njemačka' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_hr='Džibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_hr='Danska' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_hr='Dominika' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_hr='Dominikanska Republika' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_hr='Alžir' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_hr='Ekvador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_hr='Estonija' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_hr='Egipat' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_hr='Zapadna Sahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_hr='Eritreja' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_hr='Španjolska' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_hr='Etiopija' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_hr='Finska' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_hr='Fidži' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_hr='Falklandski Otoci' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_hr='Mikronezija' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_hr='Farski Otoci' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_hr='Francuska' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_hr='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_hr='Velika Britanija' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_hr='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_hr='Gruzija' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_hr='Francuska Gvajana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_hr='Gana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_hr='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_hr='Grenland' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_hr='Gambija' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_hr='Gvineja' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_hr='Guadalupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_hr='Ekvatorijalna Gvineja' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_hr='Grčka' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_hr='Južna Gruzija i Južni Sendvič Otoci' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_hr='Gvatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_hr='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_hr='Gvineja Bisau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_hr='Gvajana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_hr='Hong Kong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_hr='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_hr='Hrvatska' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_hr='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_hr='Mađarska' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_hr='Indonezija' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_hr='Irska' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_hr='Izrael' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_hr='Indija' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_hr='Britanski teritorij u Indijskom Oceanu' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_hr='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_hr='Iran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_hr='Island' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_hr='Italija' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_hr='Jamajka' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_hr='Jordan' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_hr='Japan' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_hr='Kenija' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_hr='Kirgistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_hr='Kambodža' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_hr='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_hr='Komori' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_hr='Sveti Kitts i Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_hr='Sjeverna Koreja' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_hr='Južna Koreja' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_hr='Kuvajt' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_hr='Kajmanski Otoci' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_hr='Kazahstan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_hr='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_hr='Libanon' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_hr='Sveta Lucija' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_hr='Lihtenštajn' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_hr='Šri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_hr='Liberija' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_hr='Lesoto' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_hr='Litva' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_hr='Luksemburg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_hr='Latvija' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_hr='Libija' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_hr='Maroko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_hr='Monaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_hr='Moldavija' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_hr='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_hr='Otočje Maršal' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_hr='Makedonija' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_hr='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_hr='Mianmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_hr='Mongolija' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_hr='Makao' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_hr='Sjeverni Marijani' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_hr='Martinique' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_hr='Mauritanija' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_hr='Montserat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_hr='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_hr='Mauricijus' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_hr='Maldivi' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_hr='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_hr='Meksiko' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_hr='Malezija' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_hr='Mozambik' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_hr='Namibija' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_hr='Nova Kaledonija' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_hr='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_hr='Otok Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_hr='Nigerija' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_hr='Nikaragva' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_hr='Nizozemska' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_hr='Norveška' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_hr='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_hr='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_hr='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_hr='Novi Zeland' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_hr='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_hr='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_hr='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_hr='Francuska Polinezija' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_hr='Papua Nova Gvineja' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_hr='Filipini' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_hr='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_hr='Poljska' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_hr='Sveti Pierre i Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_hr='Pitcairn' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_hr='Portoriko' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_hr='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_hr='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_hr='Paragvaj' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_hr='Katar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_hr='Reunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_hr='Rumunjska' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_hr='Rusija' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_hr='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_hr='Saudijska Arabija' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_hr='Solomonski Otoci' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_hr='Sejšeli' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_hr='Sudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_hr='Švedska' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_hr='Singapur' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_hr='Sv. Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_hr='Slovenija' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_hr='Svalbard' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_hr='Slovačka' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_hr='Sierra Leon' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_hr='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_hr='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_hr='Somalija' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_hr='Surinam' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_hr='Sao Tome i Principe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_hr='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_hr='Sirija' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_hr='Svaziland' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_hr='Turks i Caico Otoci' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_hr='Čad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_hr='Francuski Južni Teritorij' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_hr='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_hr='Tajland' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_hr='Tadžikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_hr='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_hr='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_hr='Tunis' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_hr='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_hr='Istočni Timor' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_hr='Turska' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_hr='Trinidad i Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_hr='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_hr='Tajvan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_hr='Tanzanija' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_hr='Ukrajina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_hr='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_hr='Otoci Sjedinjenih Država' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_hr='Sjedinjene Američke Države' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_hr='Urugvaj' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_hr='Uzbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_hr='Vatikan' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_hr='Sv. Vincent i Grenadini' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_hr='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_hr='Britansko Djevičansko Otočje' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_hr='Američki Djevičanski Otoci' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_hr='Vijetnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_hr='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_hr='Wallis i Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_hr='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_hr='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_hr='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_hr='Južna Afrika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_hr='Zambija' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_hr='Zimbabve' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_hr='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_hr='Srbija i Crna Gora' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_hr='Aland' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_hr='Otoci Heard i McDonald' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_hr='Crna Gora' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_hr='Srbija' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_hr='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_hr='Guersney' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_hr='Otok Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_hr='Sveti Martin' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_hr='Sveti Barthelemy' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_hr='Bonaire, Sint Eustatius i Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_hr='Kurakao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_hr='Sint Maarten' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_hr='Južni Sudan' WHERE cn_iso_2='SS';
UPDATE static_countries SET cn_short_hr='Kosovo' WHERE cn_iso_2='K1';